# Use command to generate creds
# openssl rand -base64 32
api_key: ""

database:
  journal_mode: "WAL"
  busy_timeout_ms: 5000
  synchronous: "NORMAL"
  cache_size_kb: 2147483648 # 2GiB
  temp_store: "MEMORY"
  mmap_size_bytes: 21474836480 # 20GiB

membership:
  - Dokibird
  - MintFantome

key_ttl_days: 45
