# Use command to generate creds
# openssl rand -base64 32
credentials:
  apiKey: ""

database:
  journal_mode: "WAL"
  busy_timeout_ms: 5000
  synchronous: "NORMAL"
  cache_size_kb: 200000 # 200MB
  temp_store: "MEMORY"
  mmap_size_bytes: 500000000 # 500MB

storage:
  type: "r2" # "local" or "r2"
  r2:
    accountId: ""
    accessKeyId: ""
    secretAccessKey: ""
    bucket: ""
    publicUrl: ""

channels:
  - name: doki
    numPastStreams: 3
  - name: mint
    numPastStreams: 2
  - name: test
    numPastStreams: 0
  - name: mock
    numPastStreams: 0
